name: Node.js Package
on:
  release:
    types: [created]
  push:
    branches:
      - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 12
#       - run: npm ci
#       - run: npm test

#   publish-gpr:
#     needs: build
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: read
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 12
#           registry-url: https://npm.pkg.github.com/
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/
        node-version: 14
        scope: '@codestra'
    - name: install and build
    - run:  |
        yarn install
        yarn build

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: 14
  #       registry-url: https://npm.pkg.github.com/
  #   - name: deploy
  #     env:
  #       NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #   - run: yarn deploy

    # - name: publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     cd ./dist
    #     yarn deploy