name: Node.js Package
on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/
        node-version: 14
        scope: '@codestra'
    - name: install and build
    - run:  |
        yarn install
        yarn build